export const translations = {
  en: {
    // Auth
    'welcome_back': 'Welcome back',
    'continue_tracking': 'Sign in to continue tracking your nutrition with NutriAI.',
    'login': 'Login',
    'password': 'Password',
    'email': 'Email',
    'nickname': 'Nickname',
    'confirm_password': 'Confirm Password',
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'no_account': 'Don\'t have an account?',
    'have_account': 'Already have an account?',
    'create_account': 'Create Account',
    'register_title': 'Create your account',
    'register_desc': 'Start tracking your nutrition journey today.',
    'username_or_email': 'Username or email',
    'username_placeholder': 'your_username',
    'email_placeholder': 'you@email.com',
    'password_placeholder': '********',
    'password_example': 'Example: Password123',
    'password_hint': 'Minimum 8 characters, 1 uppercase letter and 1 number',
    'password_invalid_hint': 'Password does not meet requirements',
    'password_valid_hint': 'Password is valid',
    'signup_google': 'Sign up with Google',
    'or': 'or',
    'account_details': 'Account details',
    'back': 'Back',
    'hello': 'Hello',
    'friend': 'friend',

    // Profile
    'profile': 'Profile',
    'weight': 'Weight (kg)',
    'desired_weight': 'Desired weight',
    'height': 'Height (cm)',
    'age': 'Age (years)',
    'your_goal': 'Your Goal',
    'save_profile': 'Save Profile',
    'weight_gain': 'Gain Weight',
    'weight_loss': 'Lose Weight',
    'weight_maintain': 'Maintain Weight',
    'weight_other': 'Other',
    'weight_other_placeholder': 'Write your own goal',
    'activity_level': 'Activity Level',
    'sedentary': 'Sedentary',
    'light_activity': 'Light',
    'moderate_activity': 'Moderate',
    'active': 'Active',
    'set_parameters': 'Enter your parameters',
    'params_note': 'Weight, height and age are needed to adapt your targets.',
    'save_parameters': 'Save parameters',
    'profile_title': 'Your profile',
    'profile_edit_note': 'Here you can update your parameters and account details.',
    'account_data': 'Account data',
    'tracked_days_label': 'Days tracking calories',
    'goal_days_label': 'Days goal reached',
    'view_statistics': 'View statistics',
    'health_data_section': 'Health data',
    'app_settings_section': 'App settings',
    'weight_goal_subtitle': 'Your target weight',
    'nutrition_goal_subtitle': 'Nutrition goal',
    'metric_system_title': 'Metric system',
    'metric_system_subtitle': 'Turn off to use imperial units',
    'language_title': 'Language',
    'language_subtitle': 'Choose app language',
    'language_en': 'English',
    'language_ru': 'Russian',
    'language_uk': 'Ukrainian',
    'nickname_label': 'Nickname',
    'login_label': 'Login',
    'age_years': 'years',
    'height_cm': 'cm',
    'age_unit_short': 'yr',
    'height_unit_short': 'cm',
    'goal_kcal': 'Goal',
    'norm_kcal': 'Target',
    'weight_unit_kg': 'kg',
    'weight_unit_lbs': 'lbs',
    'grams_unit_short': 'g',
    'save_profile_btn': 'Save profile',
    'delete_profile_btn': 'Delete profile',
    'logout_btn': 'Log out',
    'change_btn': 'Change',
    'confirm_selection': 'Confirm',

    // Main App
    'add_meal': 'Add Meal',
    'product': 'Product',
    'start_typing': 'Start typing: chicken, rice...',
    'grams': 'Grams',
    'calories_consumed': 'calories eaten',
    'remaining': 'Remaining',
    'overage': 'Overage',
    'carbs': 'Carbs',
    'protein': 'Protein',
    'fats': 'Fats',
    'today_eaten': 'Added:',
    'data_saved': 'Data is saved in this browser separately for each day. Changing the goal applies immediately.',
    'private_diary': 'Personal nutrition diary · data is private and stored only with you',
    'manual_entry': 'Manual Entry',
    'remember_food': 'Remember this meal',
    'add': 'Add',
    'delete': 'Delete',
    'food_found_grams': 'Product found, enter grams',
    'food_missing_manual': 'This product is not in the database, you can enter macros manually below',
    'similar_foods': 'Similar foods',
    'preview_prefix': 'Approx',
    'portion_g': 'Portion, g',
    'grams_label': 'Grams',
    'scan_food_photo_title': 'Photograph your food',
    'scan_food_photo_subtitle': 'AI will identify the food and calculate calories and macros automatically',
    'take_photo': 'Take a photo',
    'choose_from_gallery': 'Choose from gallery',
    'analyze_step_1': 'Analyzing the image',
    'analyze_step_2': 'Identifying the food',
    'analyze_step_3': 'Calculating calories and macros',
    'analyze_step_4': 'Preparing recommendations',
    'ingredients_word': 'ingredients',
    'how_much_did_you_eat': 'How much did you eat?',
    'less': 'Less',
    'more': 'More',
    'new_ingredient': 'New ingredient',
    'add_ingredient': 'Add ingredient',
    'added_to_diary_toast': 'Added to diary',
    'saved_toast': 'Saved',
    'share_ready_toast': 'Ready to share',
    'scan_food_photo': 'Scan food photo',
    'scan_food_photo_tip': 'Point the camera at your plate — AI will estimate the calories',
    'scanning_photo': 'Recognizing dish...',
    'photo_scan_error': 'Could not recognize food in this photo. Try another angle or add it manually.',
    'photo_results_title': 'Found on your photo',
    'try_again': 'Try again',
    'analyzing': 'Analyzing',
    'scan_step_ingredients': 'Identifying ingredients',
    'scan_step_calories': 'Counting calories',
    'scan_step_health': 'Scoring healthiness',
    'dont_close_tab': 'Please keep this tab open while we finish',
    'healthiness': 'Healthiness',
    'ingredients': 'Ingredients',
    'tap_to_edit': 'Edit any number - change grams and kcal/macros rescale automatically',
    'add_to_diary': 'Add to diary',
    'manual_missing_note': 'Product is missing from database. Enter macros manually for this portion.',
    'kcal': 'kcal',
    'remember_product': 'remember product',
    'add_portion': 'Add this portion',
    'today_eaten_title': 'Today eaten',
    'empty_state': 'No entries yet, add your first meal',
    'prev_day': 'Previous day',
    'next_day': 'Next day',
    'clear_day': 'Clear current day',
    'profile_goal': 'Profile goal',
    'goal_custom': 'Goal',
    'profile_goal_hint': 'You can change calories only after changing profile parameters.',
    'ring_label': 'calories eaten',
    'carbs_label': 'Carbs',
    'protein_label': 'Protein',
    'fats_label': 'Fats',
    'carbs_tip': 'Your main source of quick energy — fuels the brain and muscles.',
    'protein_tip': 'Builds and repairs muscle, keeps you full for longer.',
    'fat_tip': 'Supports hormones and vitamin absorption — needed in moderation.',
    'added': 'Added',
    'days_short': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],

    // Messages
    'invalid_credentials': 'Invalid login or password',
    'user_exists': 'User already exists',
    'account_created': 'Account created successfully',
    'logged_in': 'Logged in successfully',
    'remaining': 'Remaining',
    'overage': 'Over',
    'delete_day_confirm': 'Delete all entries for selected day?',
    'invalid_profile': 'Enter valid weight, height and age values.',
    'delete_profile_confirm': 'Delete profile and create a new account?',
    'fill_account_fields': 'Fill in all account fields.',
    'password_requirements_alert': 'Password must contain at least 8 characters, one uppercase letter and one digit.',
    'password_mismatch': 'Passwords do not match.',
    'login_required': 'Enter login/email and password.',
    'account_not_found': 'Account not found. Please register.',
    'auth_error': 'Credentials error. Try again.',
    'goal_profile_mode': 'Profile goal',
  },

  ru: {
    // Auth
    'welcome_back': 'С возвращением',
    'continue_tracking': 'Войдите, чтобы продолжить отслеживание питания с NutriAI.',
    'login': 'Логин',
    'password': 'Пароль',
    'email': 'Email',
    'nickname': 'Ник',
    'confirm_password': 'Подтвердить пароль',
    'sign_in': 'Войти',
    'sign_up': 'Зарегистрироваться',
    'no_account': 'Нет аккаунта?',
    'have_account': 'Уже есть аккаунт?',
    'create_account': 'Создать аккаунт',
    'register_title': 'Создайте аккаунт',
    'register_desc': 'Начните отслеживать питание уже сегодня.',
    'username_or_email': 'Логин или email',
    'username_placeholder': 'your_username',
    'email_placeholder': 'you@email.com',
    'password_placeholder': '********',
    'password_example': 'Пример: Password123',
    'password_hint': 'Минимум 8 символов, 1 большая буква и 1 цифра',
    'password_invalid_hint': 'Пароль не соответствует требованиям',
    'password_valid_hint': 'Пароль подходит',
    'signup_google': 'Регистрация через Google',
    'or': 'или',
    'account_details': 'Данные аккаунта',
    'back': 'Назад',
    'hello': 'Привет',
    'friend': 'друг',

    // Profile
    'profile': 'Профиль',
    'weight': 'Вес (кг)',
    'desired_weight': 'Желаемый вес',
    'height': 'Рост (см)',
    'age': 'Возраст (лет)',
    'your_goal': 'Ваша цель',
    'save_profile': 'Сохранить профиль',
    'weight_gain': 'Набрать вес',
    'weight_loss': 'Сбросить вес',
    'weight_maintain': 'Поддерживать вес',
    'weight_other': 'Другое',
    'weight_other_placeholder': 'Напишите свою цель',
    'activity_level': 'Уровень активности',
    'sedentary': 'Сидячий',
    'light_activity': 'Легкая',
    'moderate_activity': 'Средняя',
    'active': 'Высокая',
    'set_parameters': 'Укажите параметры',
    'params_note': 'Вес, рост и возраст нужны, чтобы приложение могло подстроиться под вас и предложить цель.',
    'save_parameters': 'Сохранить параметры',
    'profile_title': 'Ваш профиль',
    'profile_edit_note': 'Здесь можно изменить параметры и увидеть регистрационные данные.',
    'account_data': 'Данные аккаунта',
    'tracked_days_label': 'Дней учёта калорий',
    'goal_days_label': 'Дней с достигнутой целью',
    'view_statistics': 'Посмотреть статистику',
    'health_data_section': 'Данные о здоровье',
    'app_settings_section': 'Настройки приложения',
    'weight_goal_subtitle': 'Цель по весу',
    'nutrition_goal_subtitle': 'Цели по питанию',
    'metric_system_title': 'Метрическая система',
    'metric_system_subtitle': 'Выключите, чтобы использовать имперские единицы',
    'language_title': 'Язык',
    'language_subtitle': 'Выберите язык приложения',
    'language_en': 'Английский',
    'language_ru': 'Русский',
    'language_uk': 'Украинский',
    'nickname_label': 'Никнейм',
    'login_label': 'Логин',
    'age_years': 'лет',
    'height_cm': 'см',
    'age_unit_short': 'лет',
    'height_unit_short': 'см',
    'goal_kcal': 'Цель',
    'norm_kcal': 'Норма',
    'weight_unit_kg': 'кг',
    'weight_unit_lbs': 'фунты',
    'grams_unit_short': 'г',
    'save_profile_btn': 'Сохранить профиль',
    'delete_profile_btn': 'Удалить профиль',
    'logout_btn': 'Выйти',
    'change_btn': 'Изменить',
    'confirm_selection': 'Подтвердить',

    // Main App
    'add_meal': 'Добавить приём пищи',
    'product': 'Продукт',
    'start_typing': 'Начните вводить: курица, рис...',
    'grams': 'Грамм',
    'calories_consumed': 'калорий съедено',
    'remaining': 'Осталось',
    'overage': 'Перебор',
    'carbs': 'Углеводы',
    'protein': 'Белки',
    'fats': 'Жиры',
    'today_eaten': 'Добавлено',
    'data_saved': 'Данные сохраняются в этом браузере отдельно на каждый день. Изменение цели применяется сразу.',
    'private_diary': 'Личный дневник питания · данные приватны и хранятся только у вас',
    'manual_entry': 'Ручной ввод',
    'remember_food': 'Запомнить этот приём',
    'add': 'Добавить',
    'delete': 'Удалить',
    'food_found_grams': 'Продукт найден, укажите граммы',
    'food_missing_manual': 'Такого продукта нет в базе, можно ввести КБЖУ вручную ниже',
    'similar_foods': 'Похожие продукты',
    'preview_prefix': 'Примерно',
    'portion_g': 'Порция, г',
    'grams_label': 'Граммы',
    'scan_food_photo_title': 'Сфотографируйте еду',
    'scan_food_photo_subtitle': 'ИИ автоматически определит продукты и рассчитает КБЖУ',
    'take_photo': 'Сделать фото',
    'choose_from_gallery': 'Выбрать из галереи',
    'analyze_step_1': 'Анализируем изображение',
    'analyze_step_2': 'Определяем продукты',
    'analyze_step_3': 'Рассчитываем КБЖУ',
    'analyze_step_4': 'Формируем рекомендации',
    'ingredients_word': 'ингредиентов',
    'how_much_did_you_eat': 'Сколько вы съели?',
    'less': 'Меньше',
    'more': 'Больше',
    'new_ingredient': 'Новый ингредиент',
    'add_ingredient': 'Добавить ингредиент',
    'added_to_diary_toast': 'Добавлено в дневник',
    'saved_toast': 'Сохранено',
    'share_ready_toast': 'Готово к отправке',
    'scan_food_photo': 'Сфотографировать еду',
    'scan_food_photo_tip': 'Наведи камеру на тарелку — ИИ сам оценит калории',
    'scanning_photo': 'Распознаём блюдо...',
    'photo_scan_error': 'Не удалось распознать еду на фото. Попробуйте другой ракурс или введите вручную.',
    'photo_results_title': 'Нашли на фото',
    'try_again': 'Попробовать снова',
    'analyzing': 'Анализируем',
    'scan_step_ingredients': 'Определяем ингредиенты',
    'scan_step_calories': 'Считаем калории',
    'scan_step_health': 'Оцениваем пользу',
    'dont_close_tab': 'Не закрывайте вкладку, идёт анализ',
    'healthiness': 'Полезность',
    'ingredients': 'Ингредиенты',
    'tap_to_edit': 'Меняйте любое число - при изменении граммов калории и БЖУ пересчитаются сами',
    'add_to_diary': 'Добавить в дневник',
    'manual_missing_note': 'Такого продукта нет в базе, впишите КБЖУ вручную для этой порции.',
    'kcal': 'ккал',
    'remember_product': 'запомнить продукт',
    'add_portion': 'Добавить эту порцию',
    'today_eaten_title': 'Сегодня съедено',
    'empty_state': 'Пока пусто, добавьте первый приём пищи',
    'prev_day': 'Предыдущий день',
    'next_day': 'Следующий день',
    'clear_day': 'Очистить текущий день',
    'profile_goal': 'Цель по профилю',
    'goal_custom': 'Цель',
    'profile_goal_hint': 'Изменить калорийность можно только после изменения параметров профиля.',
    'ring_label': 'калорий съедено',
    'carbs_label': 'Углеводы',
    'protein_label': 'Белки',
    'fats_label': 'Жиры',
    'carbs_tip': 'Главный источник быстрой энергии — топливо для мозга и мышц.',
    'protein_tip': 'Строит и восстанавливает мышцы, дольше держит чувство сытости.',
    'fat_tip': 'Поддерживает гормоны и усвоение витаминов — нужны, но в меру.',
    'added': 'Добавлено',
    'days_short': ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],

    // Messages
    'invalid_credentials': 'Неверный логин или пароль',
    'user_exists': 'Пользователь уже существует',
    'account_created': 'Аккаунт создан успешно',
    'logged_in': 'Вход выполнен успешно',
    'remaining': 'Осталось',
    'overage': 'Перебор',
    'delete_day_confirm': 'Удалить все записи за выбранный день?',
    'invalid_profile': 'Укажите вес, рост и возраст правильными числами.',
    'delete_profile_confirm': 'Удалить профиль и создать новый аккаунт?',
    'fill_account_fields': 'Заполните все поля аккаунта.',
    'password_requirements_alert': 'Пароль должен содержать минимум 8 символов, одну большую букву и одну цифру.',
    'password_mismatch': 'Пароли не совпадают.',
    'login_required': 'Введите логин или email и пароль.',
    'account_not_found': 'Аккаунт не найден. Зарегистрируйтесь.',
    'auth_error': 'Ошибка учетных данных. Попробуйте снова.',
    'goal_profile_mode': 'Цель по профилю',
  },

  uk: {
    // Auth
    'welcome_back': 'З поверненням',
    'continue_tracking': 'Увійдіть, щоб продовжити відстеження харчування за допомогою NutriAI.',
    'login': 'Логін',
    'password': 'Пароль',
    'email': 'Email',
    'nickname': 'Нікнейм',
    'confirm_password': 'Підтвердити пароль',
    'sign_in': 'Увійти',
    'sign_up': 'Зареєструватися',
    'no_account': 'Немає облікового запису?',
    'have_account': 'Вже є обліковий запис?',
    'create_account': 'Створити обліковий запис',
    'register_title': 'Створіть обліковий запис',
    'register_desc': 'Почніть відстежувати харчування вже сьогодні.',
    'username_or_email': 'Логін або email',
    'username_placeholder': 'your_username',
    'email_placeholder': 'you@email.com',
    'password_placeholder': '********',
    'password_example': 'Приклад: Password123',
    'password_hint': 'Мінімум 8 символів, 1 велика літера і 1 цифра',
    'password_invalid_hint': 'Пароль не відповідає вимогам',
    'password_valid_hint': 'Пароль підходить',
    'signup_google': 'Реєстрація через Google',
    'or': 'або',
    'account_details': 'Дані облікового запису',
    'back': 'Назад',
    'hello': 'Привіт',
    'friend': 'друже',

    // Profile
    'profile': 'Профіль',
    'weight': 'Вага (кг)',
    'desired_weight': 'Бажана вага',
    'height': 'Зріст (см)',
    'age': 'Вік (років)',
    'your_goal': 'Ваша мета',
    'save_profile': 'Зберегти профіль',
    'weight_gain': 'Набрати вагу',
    'weight_loss': 'Скинути вагу',
    'weight_maintain': 'Підтримувати вагу',
    'weight_other': 'Інше',
    'weight_other_placeholder': 'Напишіть свою мету',
    'activity_level': 'Рівень активності',
    'sedentary': 'Сидячий',
    'light_activity': 'Легка',
    'moderate_activity': 'Середня',
    'active': 'Висока',
    'set_parameters': 'Вкажіть параметри',
    'params_note': 'Вага, зріст та вік потрібні, щоб застосунок підібрав вашу ціль.',
    'save_parameters': 'Зберегти параметри',
    'profile_title': 'Ваш профіль',
    'profile_edit_note': 'Тут можна змінити параметри та переглянути дані акаунта.',
    'account_data': 'Дані акаунта',
    'tracked_days_label': 'Днів обліку калорій',
    'goal_days_label': 'Днів із досягнутою ціллю',
    'view_statistics': 'Переглянути статистику',
    'health_data_section': 'Дані про здоровʼя',
    'app_settings_section': 'Налаштування застосунку',
    'weight_goal_subtitle': 'Ціль по вазі',
    'nutrition_goal_subtitle': 'Цілі по харчуванню',
    'metric_system_title': 'Метрична система',
    'metric_system_subtitle': 'Вимкніть, щоб використовувати імперські одиниці',
    'language_title': 'Мова',
    'language_subtitle': 'Оберіть мову застосунку',
    'language_en': 'Англійська',
    'language_ru': 'Російська',
    'language_uk': 'Українська',
    'nickname_label': 'Нікнейм',
    'login_label': 'Логін',
    'age_years': 'років',
    'height_cm': 'см',
    'age_unit_short': 'р',
    'height_unit_short': 'см',
    'goal_kcal': 'Ціль',
    'norm_kcal': 'Норма',
    'weight_unit_kg': 'кг',
    'weight_unit_lbs': 'фунти',
    'grams_unit_short': 'г',
    'save_profile_btn': 'Зберегти профіль',
    'delete_profile_btn': 'Видалити профіль',
    'logout_btn': 'Вийти',
    'change_btn': 'Змінити',
    'confirm_selection': 'Підтвердити',

    // Main App
    'add_meal': 'Додати прием їжі',
    'product': 'Продукт',
    'start_typing': 'Почніть писати: курка, рис...',
    'grams': 'Грам',
    'calories_consumed': 'калорій з\'їдено',
    'remaining': 'Залишилось',
    'overage': 'Перевищення',
    'carbs': 'Вуглеводи',
    'protein': 'Білки',
    'fats': 'Жири',
    'today_eaten': 'Додано',
    'data_saved': 'Дані зберігаються в цьому браузері окремо на кожен день. Зміна мети застосовується негайно.',
    'private_diary': 'Особистий щоденник харчування · дані приватні і зберігаються лише у вас',
    'manual_entry': 'Ручний ввід',
    'remember_food': 'Запам\'ятати цей прием',
    'add': 'Додати',
    'delete': 'Видалити',
    'food_found_grams': 'Продукт знайдено, вкажіть грами',
    'food_missing_manual': 'Такого продукту немає в базі, можна ввести КБЖВ вручну нижче',
    'similar_foods': 'Схожі продукти',
    'preview_prefix': 'Приблизно',
    'portion_g': 'Порція, г',
    'grams_label': 'Грами',
    'scan_food_photo_title': 'Сфотографуйте їжу',
    'scan_food_photo_subtitle': 'ШІ автоматично визначить продукти і розрахує КБЖВ',
    'take_photo': 'Зробити фото',
    'choose_from_gallery': 'Обрати з галереї',
    'analyze_step_1': 'Аналізуємо зображення',
    'analyze_step_2': 'Визначаємо продукти',
    'analyze_step_3': 'Рахуємо КБЖВ',
    'analyze_step_4': 'Формуємо рекомендації',
    'ingredients_word': 'інгредієнтів',
    'how_much_did_you_eat': 'Скільки ви з\'їли?',
    'less': 'Менше',
    'more': 'Більше',
    'new_ingredient': 'Новий інгредієнт',
    'add_ingredient': 'Додати інгредієнт',
    'added_to_diary_toast': 'Додано в щоденник',
    'saved_toast': 'Збережено',
    'share_ready_toast': 'Готово для надсилання',
    'scan_food_photo': 'Сфотографувати їжу',
    'scan_food_photo_tip': 'Наведи камеру на тарілку — ШІ сам оцінить калорії',
    'scanning_photo': 'Розпізнаємо страву...',
    'photo_scan_error': 'Не вдалося розпізнати їжу на фото. Спробуйте інший ракурс або введіть вручну.',
    'photo_results_title': 'Знайшли на фото',
    'try_again': 'Спробувати знову',
    'analyzing': 'Аналізуємо',
    'scan_step_ingredients': 'Визначаємо інгредієнти',
    'scan_step_calories': 'Рахуємо калорії',
    'scan_step_health': 'Оцінюємо користь',
    'dont_close_tab': 'Не закривайте вкладку, триває аналіз',
    'healthiness': 'Корисність',
    'ingredients': 'Інгредієнти',
    'tap_to_edit': 'Змінюйте будь-яке число - при зміні грамів калорії і БЖВ перерахуються самі',
    'add_to_diary': 'Додати в щоденник',
    'manual_missing_note': 'Такого продукту немає в базі, введіть КБЖВ вручну для цієї порції.',
    'kcal': 'ккал',
    'remember_product': 'запам\'ятати продукт',
    'add_portion': 'Додати цю порцію',
    'today_eaten_title': 'Сьогодні з\'їдено',
    'empty_state': 'Поки порожньо, додайте перший прийом їжі',
    'prev_day': 'Попередній день',
    'next_day': 'Наступний день',
    'clear_day': 'Очистити поточний день',
    'profile_goal': 'Ціль за профілем',
    'goal_custom': 'Ціль',
    'profile_goal_hint': 'Змінити калорійність можна лише після зміни параметрів профілю.',
    'ring_label': 'калорій з\'їдено',
    'carbs_label': 'Вуглеводи',
    'protein_label': 'Білки',
    'fats_label': 'Жири',
    'carbs_tip': 'Головне джерело швидкої енергії — паливо для мозку та м\'язів.',
    'protein_tip': 'Будує та відновлює м\'язи, довше тримає відчуття ситості.',
    'fat_tip': 'Підтримує гормони та засвоєння вітамінів — потрібні, але в міру.',
    'added': 'Додано',
    'days_short': ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],

    // Messages
    'invalid_credentials': 'Неправильний логін або пароль',
    'user_exists': 'Користувач вже існує',
    'account_created': 'Обліковий запис створено успішно',
    'logged_in': 'Вхід виконано успішно',
    'remaining': 'Залишилось',
    'overage': 'Перевищення',
    'delete_day_confirm': 'Видалити всі записи за вибраний день?',
    'invalid_profile': 'Вкажіть коректні вагу, зріст і вік.',
    'delete_profile_confirm': 'Видалити профіль і створити новий акаунт?',
    'fill_account_fields': 'Заповніть усі поля акаунта.',
    'password_requirements_alert': 'Пароль має містити щонайменше 8 символів, одну велику літеру та одну цифру.',
    'password_mismatch': 'Паролі не збігаються.',
    'login_required': 'Введіть логін/email і пароль.',
    'account_not_found': 'Акаунт не знайдено. Зареєструйтесь.',
    'auth_error': 'Помилка облікових даних. Спробуйте ще раз.',
    'goal_profile_mode': 'Ціль за профілем',
  },
}


